### PR TITLE
dev: end the CI, update secret and small documentation changes

### PR DESCRIPTION
**Pull request by andrepeiry**
`MainActivity.kt` wasn't formatted with respect to the KT standard. This PR format it.
Also, during this PR, the GOOGLE_SERVICE was updated.
To rerun the CI, a documentation commit was added.

### CODE REVIEW

**Comment by Pijukai** [comment]
Look at the errors in the CI , the ones about the parenthesis not closed.  Think it impact the CI ?

**Comment by andrepeiry** [comment]
Added @matttsss as reviewer so that we know the secrets are up-to-date.

**Comment by Pijukai** [comment]
Try to look into either the file path of `google-services` or the file location ?

**Comment by andrepeiry** [comment]
CI is now working, and also required for future PR.

**Review by matttsss — APPROVED** [review]
Good job! We will have to add a task to setup Sonar-Cloud.

**Review by LouisJamesVasseur — APPROVED** [review]
Perfect! The changes to the CI make sense and should allow it to work properly. I agree with @matttsss that setting up sonar should be added as a task which should allow us to move towards having a solid CI/CD pipeline to work with.

**Pull request merged**
