### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by LouisJamesVasseur**
A demo version of our application as of the Milestone 1 release.
Contains the following Screens:
- LoginScreen
- MapScreen
- ListScreen
- CardScreen
- ReviewScreen

*NOTE: Due to some unforseen GitHub problems, the Theme of the application is not included as of this release.*

As SonarCloud is not yet integrated, here is the Code Coverage as of `3b6820e` : 
image

### CODE REVIEW

**Comment by sean-prz** [comment]
So we just accept we missed the 80% code coverage ?

**Comment by andrepeiry** [comment]
> So we just accept we missed the 80% code coverage ?

@matttsss jun ran JaCoCo on its side, and the coverage, with my missing PR (#43), is at least 81%. The coaches told us that it was fine to leave my PRs open due to my GitHub issues, hence this is what the code coverage *should* be if I didn't have any problem.

**Comment by sean-prz** [comment]
> > So we just accept we missed the 80% code coverage ?
> 
> @matttsss jun ran JaCoCo on its side, and the coverage, with my missing PR (#43), is at least 81%. The coaches told us that it was fine to leave my PRs open due to my GitHub issues, hence this is what the code coverage _should_ be if I didn't have any problem.

Your PR is too big to be review now, we don't have time I suggest we just delete for now Input.kt, then we get the 80% codevarge and it doesn't need to be reviewd. We can add your #43 just after the commit

**Comment by sean-prz** [comment]
I think we should merge #71 to get 80% cc before releasing M1

**Review by matttsss — APPROVED** [review]
Let's gooooo :rocket:

**Review by andrepeiry — APPROVED** [review]
Nice work everybody ! Lots of good moments in view for later ^^

**Review by sean-prz — APPROVED** [review]

**Review by AlexandreBeeDeeBop — APPROVED** [review]
i aint reading all that

**Review by Pijukai — APPROVED** [review]
Lets's go but with more rocket  :rocket: :rocket: :rocket:

**Review by Armetiis — APPROVED** [review]
One step closer to not having my e-scooter stolen :)

**Pull request merged**
