### PR TITLE
Show in Map button

### LINKED ISSUE #348: Go to map button

### PR DESCRIPTION
**Pull request by andrepeiry**
# Content of this PR

## How
- Modify the `onClick` lambda in the button "Show in Map" in the `ParkingDetailsScreen`.
- Add a function in MapViewModel to zoom on a location. Allow to move the camera without getting the `_cameraState`.
- ParkingDetailsScreen now require the MapViewModel to navigate to a particular position.

## Small note
The documentation of the `MapViewModel` , while existing, was a bit hard to read. Maybe some clarification could be done in the polish sprint.

### Changes in code coverage
- `ui/parkingDetails` 84% to 84%
- `model/map` 82% to 82%
- *general* 82% to 82%

## Close
Close #348

### CODE REVIEW

**Review by AlexandreBeeDeeBop — COMMENTED** [review]
This is pretty straightforward, good job !
Maybe the only thing I can find to say is : 
- to please add in the ParkingDetailsScreenTest a line where you `.performClick()` on the Button where you should therefore add `.testTag()` to the modifier to be able to `verify(mockNavigationActions).navigateTo(Screen.MAP)`.

**Review by matttsss — CHANGES_REQUESTED** [review]
Sorry to bear bad news but I have a bug...
When location is enabled, the "Show in map" button works for a second but then it teleports you to your position... Could you see if you can address this?

**Comment by AlexandreBeeDeeBop** [comment]
> Sorry to bear bad news but I have a bug... When location is enabled, the "Show in map" button works for a second but then it teleports you to your position... Could you see if you can address this?

This is normal if you have location enabled. But you want it to be disabled as long as the user doesnt express his desire to teleport back to his own position ?

**Comment by matttsss** [comment]
Yes, that's correct

**Comment by andrepeiry** [comment]
> Sorry to bear bad news but I have a bug...
When location is enabled, the "Show in map" button works for a second but then it teleports you to your position... Could you see if you can address this?

> This is normal if you have location enabled. But you want it to be disabled as long as the user doesnt express his desire to teleport back to his own position ?

This would not be the desired behavior. When you click on "Show on Map", you want to see the location on map, not going back to your location.
This has been addressed in the latest commit I pushed before this comment. The reason was that the boolean value that I set with `mapViewModel.updateMapRecentering(recentering)` seems to be used in the opposite way as I thought, you can check `MapScreen:LaunchedEffect(locationEnabled)` for more investigation (basically, the function checks for `!cameraRecentering`)

**Comment by andrepeiry** [comment]
@AlexandreBeeDeeBop
> add in the ParkingDetailsScreen a .testTag() to the modifier of the clickable button.

I'm not sure what you're talking about. The `testTag` is set as a dedicated argument for the button I touched. Could you be more explicit ?

> add in the ParkingDetailsScreenTest a test where you .performClick() on that node with the new tag in order to verify(mockNavigationActions).navigateTo(Screen.MAP).

I'm gonna address this in my next commit, thank you ^^

**Comment by AlexandreBeeDeeBop** [comment]
> @AlexandreBeeDeeBop
> 
> > add in the ParkingDetailsScreen a .testTag() to the modifier of the clickable button.
> 
> I'm not sure what you're talking about. The `testTag` is set as a dedicated argument for the button I touched. Could you be more explicit ?
> 
> > add in the ParkingDetailsScreenTest a test where you .performClick() on that node with the new tag in order to verify(mockNavigationActions).navigateTo(Screen.MAP).
> 
> I'm gonna address this in my next commit, thank you ^^

i meant add a testTag for the button and you onNodeWithTag("that_testTag").performClick and verify navigation.

**Review by matttsss — APPROVED** [review]
All good with me, the bug is fixed and the new test is functional.

**Review by AlexandreBeeDeeBop — APPROVED** [review]
Perfect, you're good to merge now.

**Pull request merged**
