### PR TITLE
Enhanced Favorite Parking Cards and Slideable Tab Layout

### PR DESCRIPTION
**Pull request by Armetiis**
### Changes
1. **Redesigned Favorite Parking Cards**
   - Cards are now horizontally elongated for better visual appeal and information display.
   - Each card contains:
     - Parking title
     - Personal note (if available)
     - Icon to remove from favorites (retains existing functionality with confirmation dialog)

2. **Slideable Tab Layout**
   - Users can now switch between "Favorite Parkings" and "My Reviews" tabs by swiping horizontally.
   - This enhances the overall user experience and provides a more intuitive navigation method.

First images shows the new parking cards. Second image showcases the sliding feature.

image
image

### Rationale
The redesigned favorite parking cards focus on displaying the most relevant information to users. The personal note should be sufficient for users to recall why they favorited a particular parking. This approach prevents information overload while still providing key details. Adding more textual information will overload the card, but ... (see Future Improvements)

### Future Improvements
**Additional Parking Information**
   - Once we have appropriate icons, we can consider adding more details such as capacity, rack type, and shelter protection.
   - Using icons instead of text will maintain a clean look while providing more information without overwhelming the user.

### Testing
- Updated existing tests to accommodate the new card layout and slideable tabs.
- Added new tests to ensure proper functionality of the slideable tab layout.

### CODE REVIEW

**Review by matttsss — COMMENTED** [review]
Great feature idea, I just have a little concern with the UI behaviour when there aren't many favorite parkings on the screen. When I swipe left and only have one favorite parking, it teleports to the middle of the column for the animation instead of staying up top. Would it be possible to fix that?

**Review by sean-prz — APPROVED** [review]
Looks good and works great, nothing to complain about the code. 
I could ask chatGPT to find me something to complain about or I could be honest and just approve you ! 😉

**Comment by Armetiis** [comment]
> What do you think ?

Honestly I did the change because I also though it was more fluid for the user but this approach has severak drawbacks:

1. Load all the reviews and their corresponding parkings every time user opens the ViewProfileScreen even if they had no intention to open the tab.

2. My solution is not very clean. I think the code looks pretty weird and doesn't really respect the MVVM architecture. However, If I wanted to include this in the ViewModel, it would have added too much unnecessary complications (for this PR).

But honestly I still think it's worth it as it feels much smoother to the user

**Comment by Armetiis** [comment]
> Great feature idea, I just have a little concern with the UI behaviour when there aren't many favorite parkings on the screen. When I swipe left and only have one favorite parking, it teleports to the middle of the column for the animation instead of staying up top. Would it be possible to fix that?

Hi. Sorry I forgot to reply. This was addressed in a recent push. This should be fixed now. I also ensured that the hitbox for the slide is "the whole space" available under the tab manager.

**Review by matttsss — APPROVED** [review]
Thank you for the changes, all good for me!

**Pull request merged**
