### PR TITLE
Improve the map style

### LINKED ISSUE #35: Improve the map style
For the second sprint, the team need a cleaner map, to make development easier in paticular

The map should : 

- [x] be monochromatic to make pin stand out
- [x] be centered around Campus
- [x] be zoomed enough to see streets
- [x] have zoom in/out button for emulation

### PR DESCRIPTION
**Pull request by sean-prz**
_Closes #35_ 
### Improving the user interface of the map. 
This PR adds buttons to zoom in/out and another one to launch the process of adding new parking spots.
It also improves the style of the map to a monochromatic one, and center it by default on EPFL with an appropriate zoom level.

image

**Note** The add buttons onClick behaviour is not defined in this PR. 

-- -
Code coverage screenshot while Sonar CI is not setup
image

PS: Please let me merge my PR.
Thanks for the review, Sean

### CODE REVIEW

**Comment by Pijukai** [comment]
Maybe add some colors to the screen since it improves UX . The tests seems fine and the code coverage is above required so all good otherwise.

**Review by andrepeiry — CHANGES_REQUESTED** [review]
Nice work. Code is easy to read. The "Dynamic theme" could be improve by importing the theme of the app instead of hardcoded colors and tints (~`color = Cerulean`~ -> `color = getContainerColor(colorScheme)` or similar functions

**Comment by sean-prz** [comment]
> Nice work. Code is easy to read. The "Dynamic theme" could be improve by importing the theme of the app instead of hardcoded colors and tints (~`color = Cerulean`~ -> `color = getContainerColor(colorScheme)` or similar functions

@andrepeiry I would but I don't know how to do it. I wanted to copy Louis who did the theme but he uses hard coded value

**Review by andrepeiry — APPROVED** [review]
Everything seems fine to me, good job !

**Review by Pijukai — APPROVED** [review]
You can merge ! Thanks for the color fix

**Pull request merged**
