### PR TITLE
M2

### PR DESCRIPTION
**Pull request by andrepeiry**
# The M2 of our adventure !

Lots of new beautiful thinks have flourished during this sprint, but the most notable were

- General UI and UX improvement, through modular code and theming
- User implementation and limitation
- Parking with more details
- Review system revamp
- Usage of GPS sensor for location
- Advanced mode for parking view

Great job everybody, we can be proud of ourselves for this ! We are now in the last milestone, we can only look back and see the bright path that we have for our future !

### CODE REVIEW

**Review by sean-prz — APPROVED** [review]
I want to sleep

**Review by matttsss — APPROVED** [review]
🔥 🔥 🔥

**Review by Armetiis — APPROVED** [review]
🎊🎊🎊 (still not bringing my scooter back)

**Review by LouisJamesVasseur — APPROVED** [review]
Very happy with where our app is at for this Milestone 2 Release!

**Pull request merged**
