### PR TITLE
arch: M3 release

### PR DESCRIPTION
**Pull request by andrepeiry**
# The third and last milestone of our adventure !

Lots of new beautiful things have flourished during this sprint, but the most notable were

- Where's my Bike ?
- Offline mode
- Content management for user
- Report and Admin system
- Search bar
- Filter in the map screen
- Codacy for code coverage
- Gambling spirit
- Rack type Help screen
- Create Profile screen

Like a noble night forged in the crucible of sweat and tears, we seven have fought through every challenge with unwavering strength, and now, the dawn of success is within our grasp.

## *Note from André*

It was a real pleasure to work with all you, wishing you all the best for your next semester !

*Signed : Your beloved Scrum Daddy* 🧓

### CODE REVIEW

**Review by LouisJamesVasseur — APPROVED** [review]
Was a pleasure working with you all as well. Proud of what we've accomplished!

**Review by matttsss — APPROVED** [review]
🎉

**Review by sean-prz — APPROVED** [review]
Babye everyone, was fun

**Review by Armetiis — APPROVED** [review]
Thank you guys for everything ❄️

**Pull request merged**
