### PR TITLE
Implement user favourite parkings

### LINKED ISSUE #83: Implement Favourite Parkings Functionality
Enhance the parking system with the following updates:
- Add method to parking repository for retrieving parkings by ID list
- Implement state management in repository (does it make sense to give a parking repository to a user viewmodel?)
- Add getFavourite to UserViewModel

### PR DESCRIPTION
**Pull request by Armetiis**
Closes #83 

This PR introduces a new feature to retrieve a user's favorite parkings, improving the app's personalization capabilities.

##### UserViewModel Enhancements
- Introduced a StateFlow to manage favorite parkings
- Implemented a function to fetch and update user's favorite parkings using a ParkingRepository

##### ParkingRepository Improvements
- Added `getParkingsByListOfIds()` method for efficient bulk parking retrieval
  - Rationale: Optimizes database queries by fetching multiple parkings in a single operation

### Testing Strategy
- Updated UserViewModel unit tests to cover new StateFlow and functionality
- Added unit tests for ParkingRepository's new method
- Implemented the `getParkingsByListOfIds()` function in MockParkingRepository
- Included integration test in androidTests/ParkingRepositoryFirestore (I made them before we decided to get rid of them)

### Code Refinements
- Standardized ParkingRepository type declarations in viewModel tests
- Renamed `getParkings()` to `getAllParkings()` for clarity

### CODE REVIEW

**Review by andrepeiry — APPROVED** [review]
Good code in general.

A small improvement would be for the error message Strings to be more precise. For example, in the following location, it would be a bit hard to pinpoint rapidly where the origin of the message is :
- In `mocks/MockParkingRepository:107` : "*Error getting parkings*"
- In `model/parking/ParkingRepositoryFirestoreTest:75` : "*Failed to get parkings*"

Also, some in-code comment are a bit obvious. Comment is useful when dealing with cryptic (hard-to-read) notation / syntax-"sugar", or for long code block that can be resume in a phrase, or simply to explain a specific thing. If I take the block `model/parking/ParkingRepositoryFirestoreTest:159` :
```
// Call the method under test
parkingRepositoryFirestore.getParkingsByListOfIds(
    listOf(parking.uid),
    onSuccess ? { parkings ->
        // Assert that the returned list contains the expected Parking object
        assert(parkings.size == 1)
        assert(parkings[0] == parking)
    },
    onFailure = fail("Expected success but got failure") })
```
The first resume the 7-line code block, but "*under test*" would not be the term I'd utilize, I think "*Call method and assert results*" would be more explanatory. As for the second comment, it is too obvious and could be removed.

**Comment by Armetiis** [comment]
> * In `model/parking/ParkingRepositoryFirestoreTest:75` : "_Failed to get parkings_"
I agree, but given that the androidTests will be deleted soon enough, I don't think we should bother. To be completely honest, I made this tests before we agreed to stop making androidTests to test repositories. When I made the PR, I thought that I could leave them until a refactor PR deleted them rathor than refactoring my PR (I mentionned this briefly in the PR)

> The first resume the 7-line code block, but "_under test_" would not be the term I'd utilize, I think "_Call method and assert results_" would be more explanatory. As for the second comment, it is too obvious and could be removed.
I also agree with this. However it is consistent with the rest of the tests in this file. Should I change them all? Only this one (and have an uncossistency among the comments)? Or should I just leave as is and maybe let a future refactor PR eventually take care of this?

**Comment by andrepeiry** [comment]
> I agree, but given that the androidTests will be deleted soon enough, I don't think we should bother.
Don't. It was more a remark for general code improvement, not a blocking change that I required.

> However it is consistent with the rest of the tests in this file. Should I change them all?
It's better to have too much comment that not enough. It was just a friendly reminder not to over-do comments 😉

**Review by AlexandreBeeDeeBop — APPROVED** [review]
This is great, some of those functionalities will help me a lot to put a user's favourite parkings in a list on the profile screen.
Just resolve the conflicts and you're good to merge.

**Review by andrepeiry — APPROVED** [review]
Those tests seems nice ^^

**Pull request merged**
